/*create database*/ CREATE DATABASE LAB1

/*create table*/ CREATE TABLE TABLENAME (COLUMN1 INT PRIMARY KEY, COLUMN2 CHAR(20), COLUMN3 VARCHAR(20), COLUMN4 FLOAT) 

/*insert some rows*/ INSERT INTO TABLENAME VALUES(1, 'HIHI', 'HELLO', 20.5) ;
					 INSERT INTO TABLENAME VALUES(2, 'HOHO', 'XINCHAO', 55.5) ;
					 INSERT INTO TABLENAME VALUES(3, 'HAHA', 'AGIGATO', 45.5) ;

/*select all rows*/  SELECT * FROM TABLENAME; 

/*DESIGN database student*/ 
CREATE DATABASE STUDENT

CREATE TABLE STUDENTS (SID VARCHAR(10), SNAME VARCHAR(30), DOB VARCHAR(50), ADDRESS VARCHAR(50), ID_CARD VARCHAR(12))
CREATE TABLE COURSE (CID VARCHAR(10), CNAME VARCHAR(30), CREDIT INT)
CREATE TABLE ENROLLED(SID VARCHAR(10), CID VARCHAR(12), DAY VARCHAR(50)) 

INSERT INTO STUDENTS VALUES('1', 'LY MINH TRUNG', '26/05/2001', 'TAY NINH', '123'); 
